//auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GENDER_CHANGED = 'GENDER_CHANGED';
export const DATE_CHANGED = 'DATE_CHANGED';
export const NAME_CHANGED = 'NAME_CHANGED';
export const CONFIRM_CHANGED = 'CONFIRM_CHANGED';
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
